apiVersion: v1
kind: Pod
metadata:
  name: test-scc
spec:
  hostPID: true
  containers:
    - name: sleeper
      image: busybox
      command: ["/bin/sh", "-c", "while true; do sleep 60; done"]
      securityContext:
        runAsUser: 0
        privileged: true
      volumeMounts:
        - name: host-root
          mountPath: /host
  volumes:
    - name: host-root
      hostPath:
        path: /
        type: Directory
  restartPolicy: Never
